### ISSUE TITLE
Rmarkdown report

### ISSUE THREAD

**Issue by ursulinakoelbener** [sascha-eng/UMS-CES#1]
Hi @sascha-eng and @marco-graf 

I added another folder (named it simply "report") with an RMarkdown file. I also added the headings according to the IMRaD Sheme. In here we can report our method, findings and so on. Also it is an easy way to integrate plots and show code snippets.

https://github.com/sascha-eng/UMS-CES/blob/0e20c5c4158724348f8d9e80af4ec650239f816a/report/report.Rmd#L15

You can `pull` the RMarkdown file via RStudio to your computer. To produce a complete report containing all text, code, and results, click “Knit”. Try it out! 😄 

If you need more information about RMarkdown I would recommend the chapter: https://r4ds.had.co.nz/r-markdown.html

Cheers!

**Comment by marco-graf** [comment]
Perfect! Thank you very much, Ursulina.
