### ISSUE TITLE
Data pre-processing

### ISSUE THREAD

**Issue by marco-graf** [sascha-eng/UMS-CES#3]
Hi @ursulinakoelbener and @sascha-eng 
I added a script to the 'scripts' folder containing code for the data pre-processing part. 
Please have a look at it and feel free to comment and change. Thank you!

**Comment by ursulinakoelbener** [comment]
Hi @marco-graf 
You made a very good script: correct code, good structure and well documented.
The only thing I changed was the data loading part. As we already have another script with that part, it is not necessary to duplicate it. Further i added some foldable sections to the script..

**Comment by ursulinakoelbener** [comment]
Very well done!

**Comment by marco-graf** [comment]
Thank you very much for your comments!
